// Generated by CoffeeScript 1.7.1
(function() {
  var beautify, beautifyOpts;

  beautify = require('js-beautify').js_beautify;

  beautifyOpts = {
    indent_size: 2
  };

  module.exports = function(code) {
    return beautify(code, beautifyOpts);
  };

}).call(this);

//# sourceMappingURL=beautify.map
